#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use File::Basename qw/dirname/;

# Start by documenting the call, just so that we can get some diagnostics.
# open LOG, '>', '/tmp/flycheck.log';
# print LOG "FLYCHECK: @ARGV\n";
# print LOG "Bin: $FindBin::Bin\n";

my $root = dirname($FindBin::Bin);
my $path = $ARGV[0];
my $rel = $path;
$rel =~ s|$root/||;
my $base = $path;
$base =~ s|\.ts|| or die "Not a .ts file!";

# print LOG "Path: $path\n";
# print LOG "Rel $rel\n";

chdir $root;
# print LOG ("pwd: " . `pwd`);
# print LOG "PATH: $ENV{PATH}\n";

open TSC, '-|', 'npm run tsc 2>&1';

while ($_ = <TSC>) {
  # print LOG "LINE: $_";
  next unless /^$rel\(/;
  s/$rel/$path/g;
  print STDERR $_;
}
# close LOG;
close TSC or exit 1;

system "rm -f $base.js*"

#print STDERR "$ARGV[0]:5:5: ERROR - something\n";
