items:
  force:
    leaf elder: sword of wind

maps:
  randomize: 0.5
  force:
    valley of wind:
      page: 1
      layout:
        - $12 $14 $13 $15
        - $02 $23 $10 $12
    swamp:
      page: 4
      layout:
        - "    <      "
        - " ccccccc a "
        - " c c c c c "
        - "cccccccccc "
        - " c c c c c "
        - " ccccccccc "
        - "           "
      special objects:
        kid: (12, 42)
      exits:
        - 12 cave: oak

misc:
  community jokes: true
  permadeath: true
  wild warp: vanilla
  pity mp: 20
  hide flags: false  # can't be extended...?
  # top-level flags you can't extend also include "race", etc?

items:
  placement:
    algorithm: assumed
    temperature: infinity
    area balance factor: 1
    minimum sphere decay: 2
    minimum sphere:
      flight: 8
      sword of wind: 8
      sword of fire: 8
      sword of water: 8
      sword of thunder: 8
  mezame chests: 2
  mezame mimics: false

---
# Push all but one sword very deep
items:
  placement:
    minimum sphere:
      sword of wind: 8
      sword of fire: 8
      sword of water: 8
      sword of thunder: 8
extend: # specifically spec'd to append???
  - pick:
      - items: {placement: {minimum sphere: {sword of wind: 0}}}
      - items: {placement: {minimum sphere: {sword of fire: 0}}}
      - items: {placement: {minimum sphere: {sword of water: 0}}}
      - items: {placement: {minimum sphere: {sword of thunder: 0}}}
---
logic:
  require wild warp: true
  strategy: balanced temperature
  temperature: 2

stat tracking: false

- items:
    placement: ...
- pick:
    - weight: 2
      compose: replace # or 'add' or 'scale' ?
      items: {a: b}

# We could just have the whole thing be a LIST of configs???
#   - this might simplify merging???

# Result:
# {1aDkZpLKr54x} Iassumed/t:inf/abf:1 Gshop/statue:free/scg
# (Gtrigger|Gtrigger:free/scg:free|Gstatue:off)


vars:
  - var: x
    uniform: 10
  - var: x1
    normal: [10, 5]
  - var: z
    value: 1 - x
  - pick:

extend:
  - pick:
      - weight: 2
        items:
          unidentified: true
      - maps:
          random: 100%
      - false
  - pick:
      - items:
          unidentified: false
      - weight: 1
  - scale:
      var: x
    items:
      medical herb: 1
  - if:
      less: [{var: x}, 1]
    items:
      medical herb: 100






if: x < 5
pick:
  - weight: 2
    items:
      unidentified: true
  - scale: x + 1
    
    
    


mystery:
  - piecewise:
      - items:
          unidentified: true
        enemies:
          elements: random
      - value: x
        items:
          shuffle tradeins: true
      - towns:
          rescale shops: false
          shuffle shops: false
      - false
  - var:
      x: uniform(10)
      z: 1 - x
  - condition:
      value: x < 5
      mystery:
        
  - scale:
      value: x
      items:
        medical herb: 1
      
